server: 
  port: 3344 
  
spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/YangZhengXing0/springcloud-config-test.git
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
 

